"""RBAC services and constants."""

SYSTEM_PERMISSIONS: list[tuple[str, str]] = [
    ("org:manage", "Manage organization settings"),
    ("clinic:read", "Read clinics"),
    ("clinic:manage", "Manage clinics"),
    ("user:read", "Read users"),
    ("user:manage", "Manage users"),
    ("role:read", "Read roles"),
    ("role:assign", "Assign roles"),
    ("audit:read", "Read audit logs"),
    ("patient:read", "Read patients"),
    ("patient:create", "Create patients"),
    ("patient:update", "Update patients"),
    ("patient:delete", "Delete patients"),
    ("consent:capture", "Capture consent"),
    ("appointment:read", "Read appointments"),
    ("appointment:manage", "Manage appointments"),
    ("document:upload", "Upload documents"),
    ("document:read", "Read documents"),
    ("consultation:start", "Start consultations"),
    ("recording:write", "Write recordings"),
    ("transcript:read", "Read transcripts"),
    ("transcript:edit", "Edit transcripts"),
    ("note:read", "Read clinical notes"),
    ("note:edit", "Edit clinical notes"),
    ("note:sign", "Sign clinical notes"),
    ("prescription:write", "Write prescriptions"),
    ("ai:run", "Run AI workflows"),
    ("ai:read", "Read AI outputs"),
    ("ai:review", "Review AI suggestions"),
    ("governance:manage", "Manage AI governance"),
    ("export:run", "Run data exports"),
    ("erasure:run", "Run erasure workflows"),
    ("config:manage", "Manage system configuration"),
    ("flag:manage", "Manage feature flags"),
]

SYSTEM_ROLES: dict[str, list[str]] = {
    "org_admin": [key for key, _ in SYSTEM_PERMISSIONS],
    "clinic_admin": [
        "clinic:read",
        "clinic:manage",
        "user:read",
        "user:manage",
        "role:read",
        "role:assign",
        "patient:read",
        "patient:create",
        "patient:update",
        "appointment:read",
        "appointment:manage",
        "document:read",
        "document:upload",
        "note:read",
        "ai:read",
    ],
    "doctor": [
        "clinic:read",
        "patient:read",
        "patient:create",
        "patient:update",
        "consent:capture",
        "appointment:read",
        "appointment:manage",
        "document:read",
        "document:upload",
        "consultation:start",
        "recording:write",
        "transcript:read",
        "transcript:edit",
        "note:read",
        "note:edit",
        "note:sign",
        "prescription:write",
        "ai:run",
        "ai:read",
        "ai:review",
    ],
    "nurse": [
        "clinic:read",
        "patient:read",
        "patient:create",
        "patient:update",
        "consent:capture",
        "appointment:read",
        "appointment:manage",
        "document:read",
        "document:upload",
        "recording:write",
        "transcript:read",
        "note:read",
        "ai:run",
        "ai:read",
    ],
    "compliance_officer": [
        "audit:read",
        "patient:read",
        "document:read",
        "note:read",
        "export:run",
        "erasure:run",
        "clinic:read",
        "user:read",
        "role:read",
    ],
    "system_admin": [
        "config:manage",
        "flag:manage",
        "governance:manage",
    ],
}
